[workspace]
resolver = "3"
members = ["tests","tree_iterators_rs"]

[workspace.dependencies]
streaming-iterator = { version = "0.1.9", features = ["alloc"] }
tree_iterators_rs = { version = "3.5.0", path = "tree_iterators_rs" }
