[package]
name = "tree_iterators_rs"
version = "1.1.0"
edition = "2021"
description = "tree-iterators-rs is a library built to provide you with the iterators to easily work with tree data structures in Rust."
license = "MIT"
repository = "https://github.com/mr-adult/tree-iterators-rs"
documentation = "https://docs.rs/tree_iterators_rs/latest/tree_iterators_rs/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
streaming-iterator = "0.1.9"
serde = { version = "1.0.189",  optional = true }
serde_derive = { version = "1.0.189",  optional = true }

[features]
serde = ["dep:serde", "dep:serde_derive"]